server:
  port: 8080
debug: true

spring:
  cache:
    secondary:
      dynamic: true
      level2Enabled: true
      cachePrefix: echo1
      level2Topic: cache1:redis:secondary:topic
      caffeine:
        cacheNullValues: false
        expireAfterAccess: 600
        expireAfterWrite: 600
        refreshAfterWrite: 1
        initialCapacity: 50
        maximumSize: 50
      redis:
        cacheNullValues: false
        defaultExpiration: 36000
        cachePrefix: echo
        hostsAndPorts: 192.168.1.251:9999
        standalone:
          host: 192.168.1.251
          port: 9999
  freemarker:
    charset: UTF-8
    cache: false
    expose-request-attributes: true
    request-context-attribute: request
    expose-session-attributes: true
    content-type: text/html
    template-loader-path: classpath:/META-INF/ftl
    suffix: .ftl
    check-template-location: true
  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: true
  redis:
    cluster:
      maxRedirects: 10
      nodes:
      - 192.168.1.251:9999
    sentinel:
      master: 192.168.1.251
      sentinel:
        nodes:
        - 192.168.1.251:9999
    jedis:
      pool:
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0
      timeout: 10000
      cluster:
        nodes:
        - 192.168.1.251:9999
jdbc:
  driver:
  password: newa_newc
  jndiName: testJndiDs
  url: jdbc:mysql://192.168.1.251:3306/easytnt_sm_testing?useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true
  username: root
hibernate:
  max_fetch_depth: 10
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  format_sql: true
  hbm2ddl:
    auto: none
  jdbc:
    batch_size: 100
    fetch_size: 50
  show_sql: false
