spring:
  cache:
    # 配置两级缓存,所有缓存时间类参数单位均为毫秒
    secondary:
      dynamic: true
      level2Enabled: true
      cacheMessageTopic: echo:redis:secondary:topic
      # 两级缓存的第一级采用caffeine实现
      caffeine:
        # 默认一级缓存配置
        defaultProp:
          cacheNullValues: false
          expireAfterAccess: 600
          expireAfterWrite: 600
          refreshAfterWrite: 1
          initialCapacity: 50
          maximumSize: 50
        # 程序启动时加载的缓存
        cachesOnBoot:
        -
          name: cache1
          cacheNullValues: false
          expireAfterAccess: 600
          expireAfterWrite: 600
          refreshAfterWrite: 1
          initialCapacity: 50
          maximumSize: 50
        -
          name: cache2
          cacheNullValues: false
          expireAfterAccess: 6000
          expireAfterWrite: 6000
          refreshAfterWrite: 100
          initialCapacity: 500
          maximumSize: 500
      redis:
        cacheNullValues: false
        defaultExpiration: 36000
        cachePrefix: echo
        hostsAndPorts: 192.168.1.251:9999
        standalone:
          host: 192.168.1.251
          port: 9999